### PR TITLE
Use SQL Alchemy to connect to DB (#2)

### PR DESCRIPTION
**Pull request by abitrolly**
@patrickstephens1 I can not test this, because I don't possess MS SQL and there is no CI with DB for this repo. If that works, I can continue rewriting parts.

### CODE REVIEW

**Comment by patrickstephens1** [comment]
Hi Anatoli,  Due to the Orthodox holiday season my team won't be back until next week. We can test it then. Thanks! Patrick

**Comment by abitrolly** [comment]
@patrickstephens1 Hi Patrick. https://github.com/kvesteri/sqlalchemy-utils/issues/411 needs to be addressed for the transition.

**Comment by abitrolly** [comment]
@patrickstephens1 this is now ready for review. Connection to database is now passed using `DATABASE_URL` in addition to `secrets.py` file. This allows to easily switch backends from MS SQL to [other databases](https://docs.sqlalchemy.org/en/13/core/engines.html#supported-database) by using different `DATABASE_URL`.

The next task is to translate SQL statements from T-SQL to target database format, or use SQLAlchemy ORM. Maybe there is an ANSI SQL standard that is compatible with most databases. I don't know. I've just discovered https://comby.dev/ and I would use that for the task.

The goodness of this PR is that CI now works and is ready for tests to catch any errors resulting from translation.

**Comment by EmbeddAlex** [comment]
Hi Anatoli, thank you for your interest and ideas for the project.
I will review the code and merge it if everything is okay near time.
I think ORM works slowly than T-SQL, for this reason I would prefer to use it.
P.S. just for my interest, what is the reason for expression "echo = print" in the file_loader.py?

**Comment by abitrolly** [comment]
@EmbeddAlex the plan is to leave SQL for now, but use SQLAlchemy just to easily switch database backends. SQL is easier to modify if another type of query is needed. I looked for a way to convert SQL to target format automatically, and so far there is no ready to use solution.

`echo = print` is a simple debug pattern. I can assign echo to `lambda msg: None` to turn it off, or to a function that dumps to a file is a lot of output is produced.

**Comment by abitrolly** [comment]
@EmbeddAlex tell if you need me to split the PR to make review easier.

**Comment by abitrolly** [comment]
I also wonder how `requirements.txt` was generated? There are many dependencies that are not used. And also what do you use to run the test? Becase `pytest` couldn't discover test files out of the box.

**Comment by abitrolly** [comment]
@EmbeddAlex I didn't include integration test in the last run, because they don't pass with remote DB. The current data import procedure directs remote MS SQL to load the data from local file, which is absent in MS SQL filesystem.

https://github.com/epam/OSCI/blob/17e2e9495c962fa02a6b96b7a6188d3325bd7e09/sql_uploader.py#L35-L36

I tried to replace that with `OPENJSON` using this tutorial https://www.pauric.blog/How-To-Import-JSON-To-SQL-Server/ but I am getting `pyodbc.Error: ('HY000', 'The driver did not supply an error!')` and without MS SQL skills my chances to troubleshoot this are poor.

It would be nice if you could take a look and convert this piece for myself. Would be nice to measure if there is any performance loss after the conversion, but that's not something I could do from Linux.

**Comment by abitrolly** [comment]
Closing in favour of #7. I will rebase and add SQLAlchemy support once tests pass for loading data into MS SQL over the network. Without it I can not be sure that the port work correctly.

**Pull request closed without merging**
