### PR TITLE
Add philips.com

### PR DESCRIPTION
**Pull request by JeroenKnoops**
We want to push contributing and creating open source for Philips so please add us, so we can track progress in improving the world! :)

### CODE REVIEW

**Comment by vlad-isayko** [comment]
We have changed the target of the branch to another, which will be frozen early next month.

A new list of companies will be deployed to the cloud at the beginning of the month.

Since commits are taken into account only from the moment the company appears in the list. Then, when the list is updated in the middle of the month, only the second part of the month will be processed.

This can be misleading.

**Comment by JeroenKnoops** [comment]
Awesome!

**Comment by JeroenKnoops** [comment]
I see new releases... Maybe I did miss understand something, but I thought this would be added in the July release?

**Comment by vlad-isayko** [comment]
Hi @JeroenKnoops , I apologize for the long answer to the question. Now we cannot include your PR, because there are extra commits in this branch, please exclude them and we can include Phillips in the new release

**Comment by vlad-isayko** [comment]
Update: now there are no unnecessary commits and changes, however there is a conflict, since the file was moved

**Comment by JeroenKnoops** [comment]
I will recreate the PR!

**Pull request closed without merging**
